version: '2.1'
orbs:
  pipeline-feedback: instana/pipeline-feedback@1.1
jobs:
  build_payment_service:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - run: echo Build
  release_payment_service:
    docker:
      - image: 'instana/pipeline-feedback-orb-executor:latest'
    steps:
      - pipeline-feedback/create_release:
          release_name: 'My Awesome App release (CircleCI: ${CIRCLE_JOB}/${CIRCLE_BUILD_NUM})'
          release_scope: |
            {
              "applications": [
                { "name": "My Awesome App" }
              ],
              "services": [
                { "name": "Cool service #1" },
                {
                  "name": "Cool service #2",
                  "scopedTo": {
                    "applications": [
                      { "name": "My Cool App" }
                    ]
                  }
                }
              ]
            }
      - run: echo "Do a lot of release"
workflows:
  build_and_release_payment_service:
    jobs:
      - build_payment_service
      - release_payment_service:
          requires:
            - build_payment_service